version: "3"

services:
  netdata:
    image: justin8/netdata:armv7hf
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: "curl -ILX GET localhost:19999"
    ports:
      - "19999:19999"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "./netdata.conf:/etc/netdata/netdata.conf:ro"
